// Code generated by go generate; DO NOT EDIT.
package generate
type Artifact struct {
	AbsTileX int `json:"absTileX"`
	AbsTileY int `json:"absTileY"`
	AbsTileZ int `json:"absTileZ"`
	HolderHfid int `json:"holderHfid"`
	Id_ int `json:"id"`
	Item Item `json:"item"`
	Name_ string `json:"name"`
	SiteId int `json:"siteId"`
	StructureLocalId int `json:"structureLocalId"`
	SubregionId int `json:"subregionId"`
}
func (x *Artifact) Id() int { return x.Id_ }
func (x *Artifact) Name() string { return x.Name_ }
type DanceForm struct {
	Description string `json:"description"`
	Id_ int `json:"id"`
}
func (x *DanceForm) Id() int { return x.Id_ }
type DfWorld struct {
	Artifacts map[int]*Artifact `json:"artifacts"`
	DanceForms map[int]*DanceForm `json:"danceForms"`
	Entities map[int]*Entity `json:"entities"`
	EntityPopulations map[int]* `json:"entityPopulations"`
	HistoricalEras map[int]*HistoricalEra `json:"historicalEras"`
	HistoricalEventCollections map[int]*HistoricalEventCollection `json:"historicalEventCollections"`
	HistoricalEvents map[int]*HistoricalEvent `json:"historicalEvents"`
	HistoricalFigures map[int]*HistoricalFigure `json:"historicalFigures"`
	MusicalForms map[int]*MusicalForm `json:"musicalForms"`
	PoeticForms map[int]*PoeticForm `json:"poeticForms"`
	Regions map[int]*Region `json:"regions"`
	Sites map[int]*Site `json:"sites"`
	UndergroundRegions map[int]*UndergroundRegion `json:"undergroundRegions"`
	WorldConstructions string `json:"worldConstructions"`
	WrittenContents map[int]*WrittenContent `json:"writtenContents"`
}
type Entity struct {
	Id_ int `json:"id"`
	Name_ string `json:"name"`
}
func (x *Entity) Id() int { return x.Id_ }
func (x *Entity) Name() string { return x.Name_ }
type EntityFormerPositionLink struct {
	EndYear int `json:"endYear"`
	EntityId int `json:"entityId"`
	PositionProfileId int `json:"positionProfileId"`
	StartYear int `json:"startYear"`
}
type EntityLink struct {
	EntityId int `json:"entityId"`
	LinkStrength int `json:"linkStrength"`
	LinkType string `json:"linkType"`
}
type EntityPositionLink struct {
	EntityId int `json:"entityId"`
	PositionProfileId int `json:"positionProfileId"`
	StartYear int `json:"startYear"`
}
type EntitySquadLink struct {
	EntityId int `json:"entityId"`
	SquadId int `json:"squadId"`
	SquadPosition int `json:"squadPosition"`
	StartYear int `json:"startYear"`
}
type HfLink struct {
	Hfid int `json:"hfid"`
	LinkStrength int `json:"linkStrength"`
	LinkType string `json:"linkType"`
}
type HfSkill struct {
	Skill string `json:"skill"`
	TotalIp int `json:"totalIp"`
}
type HistoricalEra struct {
	Name_ string `json:"name"`
	StartYear int `json:"startYear"`
}
func (x *HistoricalEra) Name() string { return x.Name_ }
type HistoricalEvent struct {
	Id_ int `json:"id"`
	Seconds72 int `json:"seconds72"`
	Type string `json:"type"`
	Year int `json:"year"`
}
func (x *HistoricalEvent) Id() int { return x.Id_ }
type HistoricalEventAddHfEntityLink struct {
	CivId int `json:"civId"`
	Hfid int `json:"hfid"`
	Link string `json:"link"`
	PositionId int `json:"positionId"`
}
type HistoricalEventAddHfHfLink struct {
	Hfid int `json:"hfid"`
	HfidTarget int `json:"hfidTarget"`
}
type HistoricalEventArtifactClaimFormed struct {
	ArtifactId int `json:"artifactId"`
	Circumstance string `json:"circumstance"`
	Claim string `json:"claim"`
	EntityId int `json:"entityId"`
	HistFigureId int `json:"histFigureId"`
	PositionProfileId int `json:"positionProfileId"`
}
type HistoricalEventArtifactCreated struct {
	ArtifactId int `json:"artifactId"`
	HistFigureId int `json:"histFigureId"`
	SiteId int `json:"siteId"`
	UnitId int `json:"unitId"`
}
type HistoricalEventArtifactLost struct {
	ArtifactId int `json:"artifactId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventArtifactStored struct {
	ArtifactId int `json:"artifactId"`
	HistFigureId int `json:"histFigureId"`
	SiteId int `json:"siteId"`
	UnitId int `json:"unitId"`
}
type HistoricalEventAssumeIdentity struct {
	IdentityId int `json:"identityId"`
	TargetEnid int `json:"targetEnid"`
	TricksterHfid int `json:"tricksterHfid"`
}
type HistoricalEventAttackedSite struct {
	AttackerCivId int `json:"attackerCivId"`
	AttackerGeneralHfid int `json:"attackerGeneralHfid"`
	DefenderCivId int `json:"defenderCivId"`
	DefenderGeneralHfid int `json:"defenderGeneralHfid"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventBodyAbused struct {
	Coords string `json:"coords"`
	FeatureLayerId int `json:"featureLayerId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventCeremony struct {
	CivId int `json:"civId"`
	FeatureLayerId int `json:"featureLayerId"`
	OccasionId int `json:"occasionId"`
	ScheduleId int `json:"scheduleId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventChangeHfJob struct {
	FeatureLayerId int `json:"featureLayerId"`
	Hfid int `json:"hfid"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventChangeHfState struct {
	Coords string `json:"coords"`
	FeatureLayerId int `json:"featureLayerId"`
	Hfid int `json:"hfid"`
	Mood string `json:"mood"`
	Reason string `json:"reason"`
	SiteId int `json:"siteId"`
	State string `json:"state"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventChangedCreatureType struct {
	ChangeeHfid int `json:"changeeHfid"`
	ChangerHfid int `json:"changerHfid"`
	NewCaste string `json:"newCaste"`
	NewRace string `json:"newRace"`
	OldCaste string `json:"oldCaste"`
	OldRace string `json:"oldRace"`
}
type HistoricalEventCompetition struct {
	CivId int `json:"civId"`
	CompetitorHfid []int `json:"competitorHfid"`
	FeatureLayerId int `json:"featureLayerId"`
	OccasionId int `json:"occasionId"`
	ScheduleId int `json:"scheduleId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
	WinnerHfid int `json:"winnerHfid"`
}
type HistoricalEventCreatedSite struct {
	BuilderHfid int `json:"builderHfid"`
	CivId int `json:"civId"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventCreatedStructure struct {
	BuilderHfid int `json:"builderHfid"`
	CivId int `json:"civId"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
	StructureId int `json:"structureId"`
}
type HistoricalEventCreatedWorldConstruction struct {
	CivId int `json:"civId"`
	MasterWcid int `json:"masterWcid"`
	SiteCivId int `json:"siteCivId"`
	SiteId1 int `json:"siteId1"`
	SiteId2 int `json:"siteId2"`
	Wcid int `json:"wcid"`
}
type HistoricalEventCreatureDevoured struct {
	FeatureLayerId int `json:"featureLayerId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventEntityAllianceFormed struct {
	InitiatingEnid int `json:"initiatingEnid"`
	JoiningEnid int `json:"joiningEnid"`
}
type HistoricalEventEntityBreachFeatureLayer struct {
	CivEntityId int `json:"civEntityId"`
	FeatureLayerId int `json:"featureLayerId"`
	SiteEntityId int `json:"siteEntityId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventEntityCreated struct {
	EntityId int `json:"entityId"`
	SiteId int `json:"siteId"`
	StructureId int `json:"structureId"`
}
type HistoricalEventFailedFrameAttempt struct {
	ConvicterEnid int `json:"convicterEnid"`
	Crime string `json:"crime"`
	FooledHfid int `json:"fooledHfid"`
	FramerHfid int `json:"framerHfid"`
	TargetHfid int `json:"targetHfid"`
}
type HistoricalEventFieldBattle struct {
	AttackerCivId int `json:"attackerCivId"`
	AttackerGeneralHfid int `json:"attackerGeneralHfid"`
	Coords string `json:"coords"`
	DefenderCivId int `json:"defenderCivId"`
	DefenderGeneralHfid int `json:"defenderGeneralHfid"`
	FeatureLayerId int `json:"featureLayerId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventGamble struct {
	GamblerHfid int `json:"gamblerHfid"`
	NewAccount int `json:"newAccount"`
	OldAccount int `json:"oldAccount"`
	SiteId int `json:"siteId"`
	StructureId int `json:"structureId"`
}
type HistoricalEventHfAbducted struct {
	FeatureLayerId int `json:"featureLayerId"`
	SiteId int `json:"siteId"`
	SnatcherHfid int `json:"snatcherHfid"`
	SubregionId int `json:"subregionId"`
	TargetHfid int `json:"targetHfid"`
}
type HistoricalEventHfAttackedSite struct {
	AttackerHfid int `json:"attackerHfid"`
	DefenderCivId int `json:"defenderCivId"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventHfConvicted struct {
	ConvictedHfid int `json:"convictedHfid"`
	ConvicterEnid int `json:"convicterEnid"`
	Crime string `json:"crime"`
	PrisonMonths int `json:"prisonMonths"`
}
type HistoricalEventHfDestroyedSite struct {
	AttackerHfid int `json:"attackerHfid"`
	DefenderCivId int `json:"defenderCivId"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventHfDied struct {
	Cause string `json:"cause"`
	FeatureLayerId int `json:"featureLayerId"`
	Hfid int `json:"hfid"`
	SiteId int `json:"siteId"`
	SlayerCaste string `json:"slayerCaste"`
	SlayerHfid int `json:"slayerHfid"`
	SlayerItemId int `json:"slayerItemId"`
	SlayerRace string `json:"slayerRace"`
	SlayerShooterItemId int `json:"slayerShooterItemId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventHfGainsSecretGoal struct {
	Hfid int `json:"hfid"`
	SecretGoal string `json:"secretGoal"`
}
type HistoricalEventHfNewPet struct {
	Coords string `json:"coords"`
	FeatureLayerId int `json:"featureLayerId"`
	GroupHfid int `json:"groupHfid"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventHfRelationshipDenied struct {
	FeatureLayerId int `json:"featureLayerId"`
	Reason string `json:"reason"`
	ReasonId int `json:"reasonId"`
	Relationship string `json:"relationship"`
	SeekerHfid int `json:"seekerHfid"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
	TargetHfid int `json:"targetHfid"`
}
type HistoricalEventHfSimpleBattleEvent struct {
	FeatureLayerId int `json:"featureLayerId"`
	Group1Hfid int `json:"group1Hfid"`
	Group2Hfid int `json:"group2Hfid"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
	Subtype string `json:"subtype"`
}
type HistoricalEventHfTravel struct {
	Coords string `json:"coords"`
	FeatureLayerId int `json:"featureLayerId"`
	GroupHfid int `json:"groupHfid"`
	Return string `json:"return"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventHfWounded struct {
	FeatureLayerId int `json:"featureLayerId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
	WoundeeHfid int `json:"woundeeHfid"`
	WounderHfid int `json:"wounderHfid"`
}
type HistoricalEventHfsFormedReputationRelationship struct {
	FeatureLayerId int `json:"featureLayerId"`
	HfRep1Of2 string `json:"hfRep1Of2"`
	HfRep2Of1 string `json:"hfRep2Of1"`
	Hfid1 int `json:"hfid1"`
	Hfid2 int `json:"hfid2"`
	IdentityId1 int `json:"identityId1"`
	IdentityId2 int `json:"identityId2"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventItemStolen struct {
	Circumstance string `json:"circumstance"`
	CircumstanceId int `json:"circumstanceId"`
}
type HistoricalEventKnowledgeDiscovered struct {
	First string `json:"first"`
	Hfid int `json:"hfid"`
	Knowledge string `json:"knowledge"`
}
type HistoricalEventMasterpieceItem struct {
	EntityId int `json:"entityId"`
	Hfid int `json:"hfid"`
	SiteId int `json:"siteId"`
	SkillAtTime int `json:"skillAtTime"`
}
type HistoricalEventMerchant struct {
	DepotEntityId int `json:"depotEntityId"`
	SiteId int `json:"siteId"`
	TraderEntityId int `json:"traderEntityId"`
}
type HistoricalEventPerformance struct {
	CivId int `json:"civId"`
	FeatureLayerId int `json:"featureLayerId"`
	OccasionId int `json:"occasionId"`
	ScheduleId int `json:"scheduleId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventPlunderedSite struct {
	AttackerCivId int `json:"attackerCivId"`
	DefenderCivId int `json:"defenderCivId"`
	Detected string `json:"detected"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventProcession struct {
	CivId int `json:"civId"`
	FeatureLayerId int `json:"featureLayerId"`
	OccasionId int `json:"occasionId"`
	ScheduleId int `json:"scheduleId"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventRazedStructure struct {
	CivId int `json:"civId"`
	SiteId int `json:"siteId"`
	StructureId int `json:"structureId"`
}
type HistoricalEventReclaimSite struct {
	CivId int `json:"civId"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventRemoveHfEntityLink struct {
	CivId int `json:"civId"`
	Hfid int `json:"hfid"`
	Link string `json:"link"`
	PositionId int `json:"positionId"`
}
type HistoricalEventRemoveHfHfLink struct {
	Hfid int `json:"hfid"`
	HfidTarget int `json:"hfidTarget"`
}
type HistoricalEventSiteDispute struct {
	Dispute string `json:"dispute"`
	EntityId1 int `json:"entityId1"`
	EntityId2 int `json:"entityId2"`
	SiteId1 int `json:"siteId1"`
	SiteId2 int `json:"siteId2"`
}
type HistoricalEventSiteTakenOver struct {
	AttackerCivId int `json:"attackerCivId"`
	DefenderCivId int `json:"defenderCivId"`
	NewSiteCivId int `json:"newSiteCivId"`
	SiteCivId int `json:"siteCivId"`
	SiteId int `json:"siteId"`
}
type HistoricalEventSquadVsSquad struct {
	AHfid int `json:"aHfid"`
	ASquadId int `json:"aSquadId"`
	DEffect int `json:"dEffect"`
	DInteraction int `json:"dInteraction"`
	DNumber int `json:"dNumber"`
	DRace int `json:"dRace"`
	DSlain int `json:"dSlain"`
	DSquadId int `json:"dSquadId"`
	FeatureLayerId int `json:"featureLayerId"`
	SiteId int `json:"siteId"`
	StructureId int `json:"structureId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventTacticalSituation struct {
	ATacticianHfid int `json:"aTacticianHfid"`
	ATacticsRoll int `json:"aTacticsRoll"`
	DTacticianHfid int `json:"dTacticianHfid"`
	DTacticsRoll int `json:"dTacticsRoll"`
	FeatureLayerId int `json:"featureLayerId"`
	SiteId int `json:"siteId"`
	Situation string `json:"situation"`
	Start string `json:"start"`
	StructureId int `json:"structureId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventWrittenContentComposed struct {
	Circumstance string `json:"circumstance"`
	CircumstanceId int `json:"circumstanceId"`
	HistFigureId int `json:"histFigureId"`
	Reason string `json:"reason"`
	ReasonId int `json:"reasonId"`
	SiteId int `json:"siteId"`
	WcId int `json:"wcId"`
}
type HistoricalEventCollection struct {
	EndSeconds72 int `json:"endSeconds72"`
	EndYear int `json:"endYear"`
	Event []int `json:"event"`
	Eventcol []int `json:"eventcol"`
	Id_ int `json:"id"`
	StartSeconds72 int `json:"startSeconds72"`
	StartYear int `json:"startYear"`
	Type string `json:"type"`
}
func (x *HistoricalEventCollection) Id() int { return x.Id_ }
type HistoricalEventCollectionBattle struct {
	AttackingHfid []int `json:"attackingHfid"`
	AttackingSquadDeaths []int `json:"attackingSquadDeaths"`
	AttackingSquadEntityPop []int `json:"attackingSquadEntityPop"`
	AttackingSquadNumber []int `json:"attackingSquadNumber"`
	AttackingSquadRace []string `json:"attackingSquadRace"`
	AttackingSquadSite []int `json:"attackingSquadSite"`
	Coords string `json:"coords"`
	DefendingHfid []int `json:"defendingHfid"`
	DefendingSquadDeaths []int `json:"defendingSquadDeaths"`
	DefendingSquadEntityPop []int `json:"defendingSquadEntityPop"`
	DefendingSquadNumber []int `json:"defendingSquadNumber"`
	DefendingSquadRace []string `json:"defendingSquadRace"`
	DefendingSquadSite []int `json:"defendingSquadSite"`
	FeatureLayerId int `json:"featureLayerId"`
	IndividualMerc []string `json:"individualMerc"`
	Name_ string `json:"name"`
	NoncomHfid []int `json:"noncomHfid"`
	Outcome string `json:"outcome"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
	WarEventcol int `json:"warEventcol"`
}
func (x *HistoricalEventCollectionBattle) Name() string { return x.Name_ }
type HistoricalEventCollectionBeastAttack struct {
	Coords string `json:"coords"`
	DefendingEnid int `json:"defendingEnid"`
	FeatureLayerId int `json:"featureLayerId"`
	Ordinal int `json:"ordinal"`
	ParentEventcol int `json:"parentEventcol"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventCollectionDuel struct {
	AttackingHfid int `json:"attackingHfid"`
	Coords string `json:"coords"`
	DefendingHfid int `json:"defendingHfid"`
	FeatureLayerId int `json:"featureLayerId"`
	Ordinal int `json:"ordinal"`
	ParentEventcol int `json:"parentEventcol"`
	SiteId int `json:"siteId"`
	SubregionId int `json:"subregionId"`
}
type HistoricalEventCollectionOccasion struct {
	CivId int `json:"civId"`
	OccasionId int `json:"occasionId"`
	Ordinal int `json:"ordinal"`
}
type HistoricalEventCollectionSiteConquered struct {
	AttackingEnid int `json:"attackingEnid"`
	DefendingEnid int `json:"defendingEnid"`
	Ordinal int `json:"ordinal"`
	SiteId int `json:"siteId"`
	WarEventcol int `json:"warEventcol"`
}
type HistoricalEventCollectionWar struct {
	AggressorEntId int `json:"aggressorEntId"`
	DefenderEntId int `json:"defenderEntId"`
	Name_ string `json:"name"`
}
func (x *HistoricalEventCollectionWar) Name() string { return x.Name_ }
type HistoricalFigure struct {
	Appeared int `json:"appeared"`
	AssociatedType string `json:"associatedType"`
	BirthSeconds72 int `json:"birthSeconds72"`
	BirthYear int `json:"birthYear"`
	Caste string `json:"caste"`
	CurrentIdentityId int `json:"currentIdentityId"`
	DeathSeconds72 int `json:"deathSeconds72"`
	DeathYear int `json:"deathYear"`
	Deity string `json:"deity"`
	EntPopId int `json:"entPopId"`
	EntityFormerPositionLink []EntityFormerPositionLink `json:"entityFormerPositionLink"`
	EntityLink []EntityLink `json:"entityLink"`
	EntityPositionLink []EntityPositionLink `json:"entityPositionLink"`
	EntityReputation map[int]* `json:"entityReputation"`
	EntitySquadLink EntitySquadLink `json:"entitySquadLink"`
	Force string `json:"force"`
	Goal []string `json:"goal"`
	HfLink []HfLink `json:"hfLink"`
	HfSkill []HfSkill `json:"hfSkill"`
	HoldsArtifact int `json:"holdsArtifact"`
	Id_ int `json:"id"`
	InteractionKnowledge []string `json:"interactionKnowledge"`
	IntrigueActor IntrigueActor `json:"intrigueActor"`
	IntriguePlot []IntriguePlot `json:"intriguePlot"`
	JourneyPet []string `json:"journeyPet"`
	Name_ string `json:"name"`
	Race string `json:"race"`
	RelationshipProfileHfHistorical RelationshipProfileHfHistorical `json:"relationshipProfileHfHistorical"`
	RelationshipProfileHfVisual []RelationshipProfileHfVisual `json:"relationshipProfileHfVisual"`
	SiteLink SiteLink `json:"siteLink"`
	Sphere []string `json:"sphere"`
	UsedIdentityId int `json:"usedIdentityId"`
	VagueRelationship []VagueRelationship `json:"vagueRelationship"`
}
func (x *HistoricalFigure) Id() int { return x.Id_ }
func (x *HistoricalFigure) Name() string { return x.Name_ }
type IntrigueActor struct {
	Hfid int `json:"hfid"`
	LocalId int `json:"localId"`
	Role string `json:"role"`
	Strategy string `json:"strategy"`
}
type IntriguePlot struct {
	ActorId int `json:"actorId"`
	ArtifactId int `json:"artifactId"`
	EntityId int `json:"entityId"`
	LocalId int `json:"localId"`
	OnHold string `json:"onHold"`
	Type string `json:"type"`
}
type Item struct {
	NameString string `json:"nameString"`
	PageNumber int `json:"pageNumber"`
	PageWrittenContentId int `json:"pageWrittenContentId"`
	WritingWrittenContentId int `json:"writingWrittenContentId"`
}
type MusicalForm struct {
	Description string `json:"description"`
	Id_ int `json:"id"`
}
func (x *MusicalForm) Id() int { return x.Id_ }
type PoeticForm struct {
	Description string `json:"description"`
	Id_ int `json:"id"`
}
func (x *PoeticForm) Id() int { return x.Id_ }
type Region struct {
	Id_ int `json:"id"`
	Name_ string `json:"name"`
	Type string `json:"type"`
}
func (x *Region) Id() int { return x.Id_ }
func (x *Region) Name() string { return x.Name_ }
type RelationshipProfileHfHistorical struct {
	Fear int `json:"fear"`
	HfId int `json:"hfId"`
	Love int `json:"love"`
	Loyalty int `json:"loyalty"`
	Respect int `json:"respect"`
	Trust int `json:"trust"`
}
type RelationshipProfileHfVisual struct {
	Fear int `json:"fear"`
	HfId int `json:"hfId"`
	KnownIdentityId int `json:"knownIdentityId"`
	LastMeetSeconds72 int `json:"lastMeetSeconds72"`
	LastMeetYear int `json:"lastMeetYear"`
	Love int `json:"love"`
	Loyalty int `json:"loyalty"`
	MeetCount int `json:"meetCount"`
	RepFriendly int `json:"repFriendly"`
	RepInformationSource int `json:"repInformationSource"`
	Respect int `json:"respect"`
	Trust int `json:"trust"`
}
type Site struct {
	Id_ int `json:"id"`
	Type string `json:"type"`
}
func (x *Site) Id() int { return x.Id_ }
type SiteCamp struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteCamp) Name() string { return x.Name_ }
type SiteCave struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
	Structures map[int]*Structure `json:"structures"`
}
func (x *SiteCave) Name() string { return x.Name_ }
type SiteDarkFortress struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
	Structures map[int]*Structure `json:"structures"`
}
func (x *SiteDarkFortress) Name() string { return x.Name_ }
type SiteDarkPits struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteDarkPits) Name() string { return x.Name_ }
type SiteForestRetreat struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
	Structures map[int]*Structure `json:"structures"`
}
func (x *SiteForestRetreat) Name() string { return x.Name_ }
type SiteFortress struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
	Structures map[int]*Structure `json:"structures"`
}
func (x *SiteFortress) Name() string { return x.Name_ }
type SiteHamlet struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
	Structures map[int]*Structure `json:"structures"`
}
func (x *SiteHamlet) Name() string { return x.Name_ }
type SiteHillocks struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteHillocks) Name() string { return x.Name_ }
type SiteLabyrinth struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteLabyrinth) Name() string { return x.Name_ }
type SiteLair struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteLair) Name() string { return x.Name_ }
type SiteShrine struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteShrine) Name() string { return x.Name_ }
type SiteTown struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
	Structures map[int]*Structure `json:"structures"`
}
func (x *SiteTown) Name() string { return x.Name_ }
type SiteVault struct {
	Coords string `json:"coords"`
	Name_ string `json:"name"`
	Rectangle string `json:"rectangle"`
}
func (x *SiteVault) Name() string { return x.Name_ }
type SiteLink struct {
	EntityId int `json:"entityId"`
	LinkType string `json:"linkType"`
	OccupationId int `json:"occupationId"`
	SiteId int `json:"siteId"`
	SubId int `json:"subId"`
}
type Structure struct {
	LocalId int `json:"localId"`
	Type string `json:"type"`
}
type StructureTemple struct {
	EntityId int `json:"entityId"`
	Name_ string `json:"name"`
}
func (x *StructureTemple) Name() string { return x.Name_ }
type UndergroundRegion struct {
	Id_ int `json:"id"`
	Type string `json:"type"`
}
func (x *UndergroundRegion) Id() int { return x.Id_ }
type VagueRelationship struct {
	ChildhoodFriend string `json:"childhoodFriend"`
	Hfid int `json:"hfid"`
	JealousObsession string `json:"jealousObsession"`
	WarBuddy string `json:"warBuddy"`
}
type WrittenContent struct {
	AuthorHfid int `json:"authorHfid"`
	AuthorRoll int `json:"authorRoll"`
	Form string `json:"form"`
	FormId int `json:"formId"`
	Id_ int `json:"id"`
	Style []string `json:"style"`
	Title string `json:"title"`
}
func (x *WrittenContent) Id() int { return x.Id_ }
