builds:
  - id: linux/macos-amd64
    binary: legendsbrowser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - id: windows-amd64
    binary: LegendsBrowser
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  - format: zip
    name_template: >-
      legendsbrowser-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}macos
      {{- else if eq .Os "windows" }}win
      {{- else }}{{ .Os }}{{ end }}
    # name_template: "legendsbrowser-{{ .Version }}-{{ .Os }}"
    # replacements:
    #   darwin: macos
    #   linux: linux
    #   windows: win
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
